<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waves/recipient.proto

namespace GPBMetadata\Waves;

class Recipient
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad9010a1577617665732f726563697069656e742e70726f746f1205776176657322440a09526563697069656e7412190a0f7075626c69635f6b65795f6861736818012001280c4800120f0a05616c6961731802200128094800420b0a09726563697069656e74426b0a26636f6d2e7761766573706c6174666f726d2e70726f746f6275662e7472616e73616374696f6e5a396769746875622e636f6d2f7761766573706c6174666f726d2f676f77617665732f706b672f677270632f67656e6572617465642f7761766573aa02055761766573620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

