<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waves/transaction.proto

namespace Waves\DataTransactionData;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>waves.DataTransactionData.DataEntry</code>
 */
class DataEntry extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string key = 1;</code>
     */
    protected $key = '';
    protected $value;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $key
     *     @type int|string $int_value
     *     @type bool $bool_value
     *     @type string $binary_value
     *     @type string $string_value
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Waves\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string key = 1;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Generated from protobuf field <code>string key = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 int_value = 10;</code>
     * @return int|string
     */
    public function getIntValue()
    {
        return $this->readOneof(10);
    }

    public function hasIntValue()
    {
        return $this->hasOneof(10);
    }

    /**
     * Generated from protobuf field <code>int64 int_value = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIntValue($var)
    {
        GPBUtil::checkInt64($var);
        $this->writeOneof(10, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool bool_value = 11;</code>
     * @return bool
     */
    public function getBoolValue()
    {
        return $this->readOneof(11);
    }

    public function hasBoolValue()
    {
        return $this->hasOneof(11);
    }

    /**
     * Generated from protobuf field <code>bool bool_value = 11;</code>
     * @param bool $var
     * @return $this
     */
    public function setBoolValue($var)
    {
        GPBUtil::checkBool($var);
        $this->writeOneof(11, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes binary_value = 12;</code>
     * @return string
     */
    public function getBinaryValue()
    {
        return $this->readOneof(12);
    }

    public function hasBinaryValue()
    {
        return $this->hasOneof(12);
    }

    /**
     * Generated from protobuf field <code>bytes binary_value = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setBinaryValue($var)
    {
        GPBUtil::checkString($var, False);
        $this->writeOneof(12, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string string_value = 13;</code>
     * @return string
     */
    public function getStringValue()
    {
        return $this->readOneof(13);
    }

    public function hasStringValue()
    {
        return $this->hasOneof(13);
    }

    /**
     * Generated from protobuf field <code>string string_value = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setStringValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(13, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getValue()
    {
        return $this->whichOneof("value");
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(DataEntry::class, \Waves\DataTransactionData_DataEntry::class);

