<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waves/invoke_script_result.proto

namespace Waves\InvokeScriptResult\Call;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>waves.InvokeScriptResult.Call.Argument</code>
 */
class Argument extends \Google\Protobuf\Internal\Message
{
    protected $value;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $integer_value
     *     @type string $binary_value
     *     @type string $string_value
     *     @type bool $boolean_value
     *     @type string $case_obj
     *     @type \Waves\InvokeScriptResult\Call\Argument\PBList $list
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Waves\InvokeScriptResult::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 integer_value = 1;</code>
     * @return int|string
     */
    public function getIntegerValue()
    {
        return $this->readOneof(1);
    }

    public function hasIntegerValue()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>int64 integer_value = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIntegerValue($var)
    {
        GPBUtil::checkInt64($var);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes binary_value = 2;</code>
     * @return string
     */
    public function getBinaryValue()
    {
        return $this->readOneof(2);
    }

    public function hasBinaryValue()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>bytes binary_value = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setBinaryValue($var)
    {
        GPBUtil::checkString($var, False);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string string_value = 3;</code>
     * @return string
     */
    public function getStringValue()
    {
        return $this->readOneof(3);
    }

    public function hasStringValue()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>string string_value = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setStringValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool boolean_value = 4;</code>
     * @return bool
     */
    public function getBooleanValue()
    {
        return $this->readOneof(4);
    }

    public function hasBooleanValue()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>bool boolean_value = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setBooleanValue($var)
    {
        GPBUtil::checkBool($var);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes case_obj = 5;</code>
     * @return string
     */
    public function getCaseObj()
    {
        return $this->readOneof(5);
    }

    public function hasCaseObj()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>bytes case_obj = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCaseObj($var)
    {
        GPBUtil::checkString($var, False);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.waves.InvokeScriptResult.Call.Argument.List list = 10;</code>
     * @return \Waves\InvokeScriptResult\Call\Argument\PBList|null
     */
    public function getList()
    {
        return $this->readOneof(10);
    }

    public function hasList()
    {
        return $this->hasOneof(10);
    }

    /**
     * Generated from protobuf field <code>.waves.InvokeScriptResult.Call.Argument.List list = 10;</code>
     * @param \Waves\InvokeScriptResult\Call\Argument\PBList $var
     * @return $this
     */
    public function setList($var)
    {
        GPBUtil::checkMessage($var, \Waves\InvokeScriptResult\Call\Argument\PBList::class);
        $this->writeOneof(10, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getValue()
    {
        return $this->whichOneof("value");
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Argument::class, \Waves\InvokeScriptResult_Call_Argument::class);

