<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waves/invoke_script_result.proto

namespace Waves\InvokeScriptResult;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>waves.InvokeScriptResult.Invocation</code>
 */
class Invocation extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes dApp = 1;</code>
     */
    protected $dApp = '';
    /**
     * Generated from protobuf field <code>.waves.InvokeScriptResult.Call call = 2;</code>
     */
    protected $call = null;
    /**
     * Generated from protobuf field <code>repeated .waves.Amount payments = 3;</code>
     */
    private $payments;
    /**
     * Generated from protobuf field <code>.waves.InvokeScriptResult stateChanges = 4;</code>
     */
    protected $stateChanges = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $dApp
     *     @type \Waves\InvokeScriptResult\Call $call
     *     @type array<\Waves\Amount>|\Google\Protobuf\Internal\RepeatedField $payments
     *     @type \Waves\InvokeScriptResult $stateChanges
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Waves\InvokeScriptResult::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes dApp = 1;</code>
     * @return string
     */
    public function getDApp()
    {
        return $this->dApp;
    }

    /**
     * Generated from protobuf field <code>bytes dApp = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDApp($var)
    {
        GPBUtil::checkString($var, False);
        $this->dApp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.waves.InvokeScriptResult.Call call = 2;</code>
     * @return \Waves\InvokeScriptResult\Call|null
     */
    public function getCall()
    {
        return $this->call;
    }

    public function hasCall()
    {
        return isset($this->call);
    }

    public function clearCall()
    {
        unset($this->call);
    }

    /**
     * Generated from protobuf field <code>.waves.InvokeScriptResult.Call call = 2;</code>
     * @param \Waves\InvokeScriptResult\Call $var
     * @return $this
     */
    public function setCall($var)
    {
        GPBUtil::checkMessage($var, \Waves\InvokeScriptResult\Call::class);
        $this->call = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.Amount payments = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPayments()
    {
        return $this->payments;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.Amount payments = 3;</code>
     * @param array<\Waves\Amount>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPayments($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Waves\Amount::class);
        $this->payments = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.waves.InvokeScriptResult stateChanges = 4;</code>
     * @return \Waves\InvokeScriptResult|null
     */
    public function getStateChanges()
    {
        return $this->stateChanges;
    }

    public function hasStateChanges()
    {
        return isset($this->stateChanges);
    }

    public function clearStateChanges()
    {
        unset($this->stateChanges);
    }

    /**
     * Generated from protobuf field <code>.waves.InvokeScriptResult stateChanges = 4;</code>
     * @param \Waves\InvokeScriptResult $var
     * @return $this
     */
    public function setStateChanges($var)
    {
        GPBUtil::checkMessage($var, \Waves\InvokeScriptResult::class);
        $this->stateChanges = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Invocation::class, \Waves\InvokeScriptResult_Invocation::class);

