<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waves/block.proto

namespace Waves;

if (false) {
    /**
     * This class is deprecated. Use Waves\Block\Header instead.
     * @deprecated
     */
    class Block_Header {}
}
class_exists(Block\Header::class);
@trigger_error('Waves\Block_Header is deprecated and will be removed in the next major release. Use Waves\Block\Header instead', E_USER_DEPRECATED);

