<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waves/transaction.proto

namespace Waves;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>waves.CreateAliasTransactionData</code>
 */
class CreateAliasTransactionData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string alias = 1;</code>
     */
    protected $alias = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $alias
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Waves\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string alias = 1;</code>
     * @return string
     */
    public function getAlias()
    {
        return $this->alias;
    }

    /**
     * Generated from protobuf field <code>string alias = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAlias($var)
    {
        GPBUtil::checkString($var, True);
        $this->alias = $var;

        return $this;
    }

}

