<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waves/transaction.proto

namespace Waves;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>waves.ExchangeTransactionData</code>
 */
class ExchangeTransactionData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 amount = 1;</code>
     */
    protected $amount = 0;
    /**
     * Generated from protobuf field <code>int64 price = 2;</code>
     */
    protected $price = 0;
    /**
     * Generated from protobuf field <code>int64 buy_matcher_fee = 3;</code>
     */
    protected $buy_matcher_fee = 0;
    /**
     * Generated from protobuf field <code>int64 sell_matcher_fee = 4;</code>
     */
    protected $sell_matcher_fee = 0;
    /**
     * Generated from protobuf field <code>repeated .waves.Order orders = 5;</code>
     */
    private $orders;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $amount
     *     @type int|string $price
     *     @type int|string $buy_matcher_fee
     *     @type int|string $sell_matcher_fee
     *     @type \Waves\Order[]|\Google\Protobuf\Internal\RepeatedField $orders
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Waves\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 amount = 1;</code>
     * @return int|string
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>int64 amount = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkInt64($var);
        $this->amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 price = 2;</code>
     * @return int|string
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Generated from protobuf field <code>int64 price = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkInt64($var);
        $this->price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 buy_matcher_fee = 3;</code>
     * @return int|string
     */
    public function getBuyMatcherFee()
    {
        return $this->buy_matcher_fee;
    }

    /**
     * Generated from protobuf field <code>int64 buy_matcher_fee = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBuyMatcherFee($var)
    {
        GPBUtil::checkInt64($var);
        $this->buy_matcher_fee = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 sell_matcher_fee = 4;</code>
     * @return int|string
     */
    public function getSellMatcherFee()
    {
        return $this->sell_matcher_fee;
    }

    /**
     * Generated from protobuf field <code>int64 sell_matcher_fee = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSellMatcherFee($var)
    {
        GPBUtil::checkInt64($var);
        $this->sell_matcher_fee = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.Order orders = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOrders()
    {
        return $this->orders;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.Order orders = 5;</code>
     * @param \Waves\Order[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOrders($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Waves\Order::class);
        $this->orders = $arr;

        return $this;
    }

}

