<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waves/invoke_script_result.proto

namespace Waves;

if (false) {
    /**
     * This class is deprecated. Use Waves\InvokeScriptResult\Reissue instead.
     * @deprecated
     */
    class InvokeScriptResult_Reissue {}
}
class_exists(InvokeScriptResult\Reissue::class);
@trigger_error('Waves\InvokeScriptResult_Reissue is deprecated and will be removed in the next major release. Use Waves\InvokeScriptResult\Reissue instead', E_USER_DEPRECATED);

