<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waves/invoke_script_result.proto

namespace Waves;

if (false) {
    /**
     * This class is deprecated. Use Waves\InvokeScriptResult\Issue instead.
     * @deprecated
     */
    class InvokeScriptResult_Issue {}
}
class_exists(InvokeScriptResult\Issue::class);
@trigger_error('Waves\InvokeScriptResult_Issue is deprecated and will be removed in the next major release. Use Waves\InvokeScriptResult\Issue instead', E_USER_DEPRECATED);

