<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waves/invoke_script_result.proto

namespace Waves;

if (false) {
    /**
     * This class is deprecated. Use Waves\InvokeScriptResult\ErrorMessage instead.
     * @deprecated
     */
    class InvokeScriptResult_ErrorMessage {}
}
class_exists(InvokeScriptResult\ErrorMessage::class);
@trigger_error('Waves\InvokeScriptResult_ErrorMessage is deprecated and will be removed in the next major release. Use Waves\InvokeScriptResult\ErrorMessage instead', E_USER_DEPRECATED);

