<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waves/transaction.proto

namespace Waves;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>waves.InvokeScriptTransactionData</code>
 */
class InvokeScriptTransactionData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.waves.Recipient d_app = 1;</code>
     */
    protected $d_app = null;
    /**
     * Generated from protobuf field <code>bytes function_call = 2;</code>
     */
    protected $function_call = '';
    /**
     * Generated from protobuf field <code>repeated .waves.Amount payments = 3;</code>
     */
    private $payments;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Waves\Recipient $d_app
     *     @type string $function_call
     *     @type \Waves\Amount[]|\Google\Protobuf\Internal\RepeatedField $payments
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Waves\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.waves.Recipient d_app = 1;</code>
     * @return \Waves\Recipient
     */
    public function getDApp()
    {
        return isset($this->d_app) ? $this->d_app : null;
    }

    public function hasDApp()
    {
        return isset($this->d_app);
    }

    public function clearDApp()
    {
        unset($this->d_app);
    }

    /**
     * Generated from protobuf field <code>.waves.Recipient d_app = 1;</code>
     * @param \Waves\Recipient $var
     * @return $this
     */
    public function setDApp($var)
    {
        GPBUtil::checkMessage($var, \Waves\Recipient::class);
        $this->d_app = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes function_call = 2;</code>
     * @return string
     */
    public function getFunctionCall()
    {
        return $this->function_call;
    }

    /**
     * Generated from protobuf field <code>bytes function_call = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFunctionCall($var)
    {
        GPBUtil::checkString($var, False);
        $this->function_call = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.Amount payments = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPayments()
    {
        return $this->payments;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.Amount payments = 3;</code>
     * @param \Waves\Amount[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPayments($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Waves\Amount::class);
        $this->payments = $arr;

        return $this;
    }

}

