<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waves/invoke_script_result.proto

namespace Waves;

if (false) {
    /**
     * This class is deprecated. Use Waves\InvokeScriptResult\Payment instead.
     * @deprecated
     */
    class InvokeScriptResult_Payment {}
}
class_exists(InvokeScriptResult\Payment::class);
@trigger_error('Waves\InvokeScriptResult_Payment is deprecated and will be removed in the next major release. Use Waves\InvokeScriptResult\Payment instead', E_USER_DEPRECATED);

