<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waves/invoke_script_result.proto

namespace Waves;

if (false) {
    /**
     * This class is deprecated. Use Waves\InvokeScriptResult\SponsorFee instead.
     * @deprecated
     */
    class InvokeScriptResult_SponsorFee {}
}
class_exists(InvokeScriptResult\SponsorFee::class);
@trigger_error('Waves\InvokeScriptResult_SponsorFee is deprecated and will be removed in the next major release. Use Waves\InvokeScriptResult\SponsorFee instead', E_USER_DEPRECATED);

