<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waves/invoke_script_result.proto

namespace Waves;

if (false) {
    /**
     * This class is deprecated. Use Waves\InvokeScriptResult\Burn instead.
     * @deprecated
     */
    class InvokeScriptResult_Burn {}
}
class_exists(InvokeScriptResult\Burn::class);
@trigger_error('Waves\InvokeScriptResult_Burn is deprecated and will be removed in the next major release. Use Waves\InvokeScriptResult\Burn instead', E_USER_DEPRECATED);

