<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waves/transaction.proto

namespace Waves;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>waves.LeaseCancelTransactionData</code>
 */
class LeaseCancelTransactionData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes lease_id = 1;</code>
     */
    protected $lease_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $lease_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Waves\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes lease_id = 1;</code>
     * @return string
     */
    public function getLeaseId()
    {
        return $this->lease_id;
    }

    /**
     * Generated from protobuf field <code>bytes lease_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setLeaseId($var)
    {
        GPBUtil::checkString($var, False);
        $this->lease_id = $var;

        return $this;
    }

}

