<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waves/transaction.proto

namespace Waves;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>waves.LeaseTransactionData</code>
 */
class LeaseTransactionData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.waves.Recipient recipient = 1;</code>
     */
    protected $recipient = null;
    /**
     * Generated from protobuf field <code>int64 amount = 2;</code>
     */
    protected $amount = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Waves\Recipient $recipient
     *     @type int|string $amount
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Waves\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.waves.Recipient recipient = 1;</code>
     * @return \Waves\Recipient
     */
    public function getRecipient()
    {
        return isset($this->recipient) ? $this->recipient : null;
    }

    public function hasRecipient()
    {
        return isset($this->recipient);
    }

    public function clearRecipient()
    {
        unset($this->recipient);
    }

    /**
     * Generated from protobuf field <code>.waves.Recipient recipient = 1;</code>
     * @param \Waves\Recipient $var
     * @return $this
     */
    public function setRecipient($var)
    {
        GPBUtil::checkMessage($var, \Waves\Recipient::class);
        $this->recipient = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 amount = 2;</code>
     * @return int|string
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>int64 amount = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkInt64($var);
        $this->amount = $var;

        return $this;
    }

}

