<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waves/transaction.proto

namespace Waves;

if (false) {
    /**
     * This class is deprecated. Use Waves\MassTransferTransactionData\Transfer instead.
     * @deprecated
     */
    class MassTransferTransactionData_Transfer {}
}
class_exists(MassTransferTransactionData\Transfer::class);
@trigger_error('Waves\MassTransferTransactionData_Transfer is deprecated and will be removed in the next major release. Use Waves\MassTransferTransactionData\Transfer instead', E_USER_DEPRECATED);

