<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waves/transaction.proto

namespace Waves;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>waves.MassTransferTransactionData</code>
 */
class MassTransferTransactionData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes asset_id = 1;</code>
     */
    protected $asset_id = '';
    /**
     * Generated from protobuf field <code>repeated .waves.MassTransferTransactionData.Transfer transfers = 2;</code>
     */
    private $transfers;
    /**
     * Generated from protobuf field <code>bytes attachment = 3;</code>
     */
    protected $attachment = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $asset_id
     *     @type \Waves\MassTransferTransactionData\Transfer[]|\Google\Protobuf\Internal\RepeatedField $transfers
     *     @type string $attachment
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Waves\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes asset_id = 1;</code>
     * @return string
     */
    public function getAssetId()
    {
        return $this->asset_id;
    }

    /**
     * Generated from protobuf field <code>bytes asset_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAssetId($var)
    {
        GPBUtil::checkString($var, False);
        $this->asset_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.MassTransferTransactionData.Transfer transfers = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTransfers()
    {
        return $this->transfers;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.MassTransferTransactionData.Transfer transfers = 2;</code>
     * @param \Waves\MassTransferTransactionData\Transfer[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTransfers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Waves\MassTransferTransactionData\Transfer::class);
        $this->transfers = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes attachment = 3;</code>
     * @return string
     */
    public function getAttachment()
    {
        return $this->attachment;
    }

    /**
     * Generated from protobuf field <code>bytes attachment = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAttachment($var)
    {
        GPBUtil::checkString($var, False);
        $this->attachment = $var;

        return $this;
    }

}

