<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waves/block.proto

namespace Waves;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>waves.MicroBlock</code>
 */
class MicroBlock extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 version = 1;</code>
     */
    protected $version = 0;
    /**
     * Generated from protobuf field <code>bytes reference = 2;</code>
     */
    protected $reference = '';
    /**
     * Generated from protobuf field <code>bytes updated_block_signature = 3;</code>
     */
    protected $updated_block_signature = '';
    /**
     * Generated from protobuf field <code>bytes sender_public_key = 4;</code>
     */
    protected $sender_public_key = '';
    /**
     * Generated from protobuf field <code>repeated .waves.SignedTransaction transactions = 5;</code>
     */
    private $transactions;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $version
     *     @type string $reference
     *     @type string $updated_block_signature
     *     @type string $sender_public_key
     *     @type \Waves\SignedTransaction[]|\Google\Protobuf\Internal\RepeatedField $transactions
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Waves\Block::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 version = 1;</code>
     * @return int
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>int32 version = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkInt32($var);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes reference = 2;</code>
     * @return string
     */
    public function getReference()
    {
        return $this->reference;
    }

    /**
     * Generated from protobuf field <code>bytes reference = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setReference($var)
    {
        GPBUtil::checkString($var, False);
        $this->reference = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes updated_block_signature = 3;</code>
     * @return string
     */
    public function getUpdatedBlockSignature()
    {
        return $this->updated_block_signature;
    }

    /**
     * Generated from protobuf field <code>bytes updated_block_signature = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUpdatedBlockSignature($var)
    {
        GPBUtil::checkString($var, False);
        $this->updated_block_signature = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes sender_public_key = 4;</code>
     * @return string
     */
    public function getSenderPublicKey()
    {
        return $this->sender_public_key;
    }

    /**
     * Generated from protobuf field <code>bytes sender_public_key = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSenderPublicKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->sender_public_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.SignedTransaction transactions = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTransactions()
    {
        return $this->transactions;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.SignedTransaction transactions = 5;</code>
     * @param \Waves\SignedTransaction[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTransactions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Waves\SignedTransaction::class);
        $this->transactions = $arr;

        return $this;
    }

}

