<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waves/order.proto

namespace Waves;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>waves.Order</code>
 */
class Order extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 chain_id = 1;</code>
     */
    protected $chain_id = 0;
    /**
     * Generated from protobuf field <code>bytes sender_public_key = 2;</code>
     */
    protected $sender_public_key = '';
    /**
     * Generated from protobuf field <code>bytes matcher_public_key = 3;</code>
     */
    protected $matcher_public_key = '';
    /**
     * Generated from protobuf field <code>.waves.AssetPair asset_pair = 4;</code>
     */
    protected $asset_pair = null;
    /**
     * Generated from protobuf field <code>.waves.Order.Side order_side = 5;</code>
     */
    protected $order_side = 0;
    /**
     * Generated from protobuf field <code>int64 amount = 6;</code>
     */
    protected $amount = 0;
    /**
     * Generated from protobuf field <code>int64 price = 7;</code>
     */
    protected $price = 0;
    /**
     * Generated from protobuf field <code>int64 timestamp = 8;</code>
     */
    protected $timestamp = 0;
    /**
     * Generated from protobuf field <code>int64 expiration = 9;</code>
     */
    protected $expiration = 0;
    /**
     * Generated from protobuf field <code>.waves.Amount matcher_fee = 10;</code>
     */
    protected $matcher_fee = null;
    /**
     * Generated from protobuf field <code>int32 version = 11;</code>
     */
    protected $version = 0;
    /**
     * Generated from protobuf field <code>repeated bytes proofs = 12;</code>
     */
    private $proofs;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $chain_id
     *     @type string $sender_public_key
     *     @type string $matcher_public_key
     *     @type \Waves\AssetPair $asset_pair
     *     @type int $order_side
     *     @type int|string $amount
     *     @type int|string $price
     *     @type int|string $timestamp
     *     @type int|string $expiration
     *     @type \Waves\Amount $matcher_fee
     *     @type int $version
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $proofs
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Waves\Order::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 chain_id = 1;</code>
     * @return int
     */
    public function getChainId()
    {
        return $this->chain_id;
    }

    /**
     * Generated from protobuf field <code>int32 chain_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setChainId($var)
    {
        GPBUtil::checkInt32($var);
        $this->chain_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes sender_public_key = 2;</code>
     * @return string
     */
    public function getSenderPublicKey()
    {
        return $this->sender_public_key;
    }

    /**
     * Generated from protobuf field <code>bytes sender_public_key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSenderPublicKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->sender_public_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes matcher_public_key = 3;</code>
     * @return string
     */
    public function getMatcherPublicKey()
    {
        return $this->matcher_public_key;
    }

    /**
     * Generated from protobuf field <code>bytes matcher_public_key = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMatcherPublicKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->matcher_public_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.waves.AssetPair asset_pair = 4;</code>
     * @return \Waves\AssetPair
     */
    public function getAssetPair()
    {
        return isset($this->asset_pair) ? $this->asset_pair : null;
    }

    public function hasAssetPair()
    {
        return isset($this->asset_pair);
    }

    public function clearAssetPair()
    {
        unset($this->asset_pair);
    }

    /**
     * Generated from protobuf field <code>.waves.AssetPair asset_pair = 4;</code>
     * @param \Waves\AssetPair $var
     * @return $this
     */
    public function setAssetPair($var)
    {
        GPBUtil::checkMessage($var, \Waves\AssetPair::class);
        $this->asset_pair = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.waves.Order.Side order_side = 5;</code>
     * @return int
     */
    public function getOrderSide()
    {
        return $this->order_side;
    }

    /**
     * Generated from protobuf field <code>.waves.Order.Side order_side = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setOrderSide($var)
    {
        GPBUtil::checkEnum($var, \Waves\Order\Side::class);
        $this->order_side = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 amount = 6;</code>
     * @return int|string
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>int64 amount = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkInt64($var);
        $this->amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 price = 7;</code>
     * @return int|string
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Generated from protobuf field <code>int64 price = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkInt64($var);
        $this->price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 8;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 expiration = 9;</code>
     * @return int|string
     */
    public function getExpiration()
    {
        return $this->expiration;
    }

    /**
     * Generated from protobuf field <code>int64 expiration = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpiration($var)
    {
        GPBUtil::checkInt64($var);
        $this->expiration = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.waves.Amount matcher_fee = 10;</code>
     * @return \Waves\Amount
     */
    public function getMatcherFee()
    {
        return isset($this->matcher_fee) ? $this->matcher_fee : null;
    }

    public function hasMatcherFee()
    {
        return isset($this->matcher_fee);
    }

    public function clearMatcherFee()
    {
        unset($this->matcher_fee);
    }

    /**
     * Generated from protobuf field <code>.waves.Amount matcher_fee = 10;</code>
     * @param \Waves\Amount $var
     * @return $this
     */
    public function setMatcherFee($var)
    {
        GPBUtil::checkMessage($var, \Waves\Amount::class);
        $this->matcher_fee = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 version = 11;</code>
     * @return int
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>int32 version = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkInt32($var);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes proofs = 12;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getProofs()
    {
        return $this->proofs;
    }

    /**
     * Generated from protobuf field <code>repeated bytes proofs = 12;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setProofs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->proofs = $arr;

        return $this;
    }

}

