<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waves/recipient.proto

namespace Waves;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>waves.Recipient</code>
 */
class Recipient extends \Google\Protobuf\Internal\Message
{
    protected $recipient;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $public_key_hash
     *           First 20 bytes of the result of the Keccak256(Blake2b256(publicKey)) hashing function.
     *     @type string $alias
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Waves\Recipient::initOnce();
        parent::__construct($data);
    }

    /**
     * First 20 bytes of the result of the Keccak256(Blake2b256(publicKey)) hashing function.
     *
     * Generated from protobuf field <code>bytes public_key_hash = 1;</code>
     * @return string
     */
    public function getPublicKeyHash()
    {
        return $this->readOneof(1);
    }

    public function hasPublicKeyHash()
    {
        return $this->hasOneof(1);
    }

    /**
     * First 20 bytes of the result of the Keccak256(Blake2b256(publicKey)) hashing function.
     *
     * Generated from protobuf field <code>bytes public_key_hash = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPublicKeyHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string alias = 2;</code>
     * @return string
     */
    public function getAlias()
    {
        return $this->readOneof(2);
    }

    public function hasAlias()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>string alias = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAlias($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getRecipient()
    {
        return $this->whichOneof("recipient");
    }

}

