<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waves/transaction.proto

namespace Waves;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>waves.SignedTransaction</code>
 */
class SignedTransaction extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated bytes proofs = 2;</code>
     */
    private $proofs;
    protected $transaction;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Waves\Transaction $waves_transaction
     *     @type string $ethereum_transaction
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $proofs
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Waves\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.waves.Transaction waves_transaction = 1;</code>
     * @return \Waves\Transaction|null
     */
    public function getWavesTransaction()
    {
        return $this->readOneof(1);
    }

    public function hasWavesTransaction()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.waves.Transaction waves_transaction = 1;</code>
     * @param \Waves\Transaction $var
     * @return $this
     */
    public function setWavesTransaction($var)
    {
        GPBUtil::checkMessage($var, \Waves\Transaction::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes ethereum_transaction = 3;</code>
     * @return string
     */
    public function getEthereumTransaction()
    {
        return $this->readOneof(3);
    }

    public function hasEthereumTransaction()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>bytes ethereum_transaction = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setEthereumTransaction($var)
    {
        GPBUtil::checkString($var, False);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes proofs = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getProofs()
    {
        return $this->proofs;
    }

    /**
     * Generated from protobuf field <code>repeated bytes proofs = 2;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setProofs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->proofs = $arr;

        return $this;
    }

    /**
     * @return string
     */
    public function getTransaction()
    {
        return $this->whichOneof("transaction");
    }

}

