<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waves/transaction.proto

namespace Waves;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>waves.TransferTransactionData</code>
 */
class TransferTransactionData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.waves.Recipient recipient = 1;</code>
     */
    protected $recipient = null;
    /**
     * Generated from protobuf field <code>.waves.Amount amount = 2;</code>
     */
    protected $amount = null;
    /**
     * Generated from protobuf field <code>bytes attachment = 3;</code>
     */
    protected $attachment = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Waves\Recipient $recipient
     *     @type \Waves\Amount $amount
     *     @type string $attachment
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Waves\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.waves.Recipient recipient = 1;</code>
     * @return \Waves\Recipient
     */
    public function getRecipient()
    {
        return isset($this->recipient) ? $this->recipient : null;
    }

    public function hasRecipient()
    {
        return isset($this->recipient);
    }

    public function clearRecipient()
    {
        unset($this->recipient);
    }

    /**
     * Generated from protobuf field <code>.waves.Recipient recipient = 1;</code>
     * @param \Waves\Recipient $var
     * @return $this
     */
    public function setRecipient($var)
    {
        GPBUtil::checkMessage($var, \Waves\Recipient::class);
        $this->recipient = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.waves.Amount amount = 2;</code>
     * @return \Waves\Amount
     */
    public function getAmount()
    {
        return isset($this->amount) ? $this->amount : null;
    }

    public function hasAmount()
    {
        return isset($this->amount);
    }

    public function clearAmount()
    {
        unset($this->amount);
    }

    /**
     * Generated from protobuf field <code>.waves.Amount amount = 2;</code>
     * @param \Waves\Amount $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkMessage($var, \Waves\Amount::class);
        $this->amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes attachment = 3;</code>
     * @return string
     */
    public function getAttachment()
    {
        return $this->attachment;
    }

    /**
     * Generated from protobuf field <code>bytes attachment = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAttachment($var)
    {
        GPBUtil::checkString($var, False);
        $this->attachment = $var;

        return $this;
    }

}

