name: PHP selftest

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run selftest suite
      env:
        WAVESKIT_SEED: ${{ secrets.WAVESKIT_SEED }}
        WAVESKIT_NODES: ${{ secrets.WAVESKIT_NODES }}
      run: composer run-script test --timeout=3600
